import type { SelectOption, OptionGroup } from './types';

export const proportionOptions: SelectOption[] = [
    { value: 'chibi-1-2-ratio', label: 'Chibi (Rasio 1:2)' },
    { value: 'chibi-1-3-ratio', label: 'Chibi (Rasio 1:3)' },
    { value: 'chibi-1-3.8-ratio', label: 'Chibi (Rasio 1:3.8)' },
    { value: 'chibi-1-4-ratio', label: 'Chibi (Rasio 1:4)' },
    { value: 'slim-elegant-chibi-1-4-ratio', label: 'Chibi Ramping Elegan (Rasio 1:4)' },
    { value: 'cute-cartoon-1-4-ratio', label: 'Kartun Lucu (Rasio 1:4)' },
    { value: 'standard-anime-1-6-ratio', label: 'Anime Standar (Rasio 1:6)' },
    { value: 'semi-realistic-1-7-ratio', label: 'Semi-realistis (Rasio 1:7)' },
    { value: 'realistic-human-1-7.5-ratio', label: 'Manusia Realistis (Rasio 1:7.5)' },
    { value: 'slim-elegant-tall-1-8-ratio', label: 'Ramping & Tinggi Elegan (Rasio 1:8)' },
    { value: 'stylized-fashion-illustration', label: 'Ilustrasi Fashion Stylized' },
    { value: 'heroic-v-shape-torso', label: 'Heroik (Badan V-shape)' },
    { value: 'cute-mascot-character', label: 'Karakter Maskot Lucu' },
    { value: 'western-comic-book-style-90s', label: 'Gaya Komik Barat (90-an)' },
    { value: 'modern-american-comic-style', label: 'Gaya Komik Amerika Modern' },
    { value: 'pixar-style-character', label: 'Karakter Gaya Pixar' },
    { value: 'disney-style-character-classic', label: 'Karakter Gaya Disney (Klasik)' },
    { value: 'disney-style-character-modern', label: 'Karakter Gaya Disney (Modern)' },
    { value: 'ghibli-style-character', label: 'Karakter Gaya Ghibli' },
    { value: 'tim-burton-esque-lanky', label: 'Gaya Tim Burton (Jangkung & Kurus)' },
    { value: 'kawaii-plush-toy', label: 'Boneka Plush Kawaii' },
    { value: 'rubber-hose-animation-1930s', label: 'Animasi Rubber Hose (1930-an)' },
    { value: 'video-game-character-realistic', label: 'Karakter Game (Realistis)' },
    { value: 'video-game-character-stylized', label: 'Karakter Game (Stylized)' },
    { value: 'manga-shonen-style', label: 'Gaya Manga Shonen' },
    { value: 'manga-shoujo-style', label: 'Gaya Manga Shoujo' },
];

export const materialOptions: OptionGroup[] = [
    {
        label: 'Gaya 3D',
        options: [
            { value: '3d-clean-modern', label: '3D Modern & Bersih' },
            { value: 'smooth-3d-render', label: '3D Render Halus' },
            { value: 'photorealistic-3d-render', label: '3D Render Fotorealistis' },
            { value: 'stylized-3d-character', label: 'Karakter 3D Stylized' },
            { value: 'low-poly-3d', label: '3D Low Poly' },
            { value: 'isometric-3d', label: '3D Isometrik' },
            { value: 'stop-motion-clay-figure', label: 'Figur Tanah Liat Stop-motion' },
            { value: 'glossy-vinyl-figure', label: 'Figur Vinyl Mengkilap' },
            { value: 'plush-toy-fabric', label: 'Kain Boneka Plush' },
            { value: '3d-sculpted-model', label: 'Model Pahat 3D' },
        ]
    },
    {
        label: 'Lukisan Digital 2D',
        options: [
            { value: 'digital-painting-detailed', label: 'Lukisan Digital (Detail)' },
            { value: 'semi-realistic-painting', label: 'Lukisan Semi-Realistis' },
            { value: 'concept-art-sketchy', label: 'Seni Konsep (Sketsa)' },
            { value: 'storybook-illustration', label: 'Ilustrasi Buku Cerita' },
            { value: 'cel-shaded-anime', label: 'Anime Cel-shaded' },
            { value: 'soft-shaded-anime', label: 'Anime Soft-shaded' },
            { value: 'hand-drawn-2d-cartoon', label: 'Kartun 2D Gambar Tangan' },
            { value: 'pixel-art-16-bit', label: 'Pixel Art (16-bit)' },
            { value: 'airbrush-art', label: 'Seni Airbrush' },
            { value: 'digital-watercolor', label: 'Cat Air Digital' },
        ]
    },
    {
        label: 'Gaya Vektor & Grafis',
        options: [
            { value: 'clean-vector-art', label: 'Seni Vektor Bersih' },
            { value: 'flat-illustration', label: 'Ilustrasi Datar (Flat)' },
            { value: 'gradient-vector-art', label: 'Seni Vektor Gradasi' },
            { value: 'glowing-neon-line-art', label: 'Seni Garis Neon Bercahaya' },
            { value: 'risograph-print-style', label: 'Gaya Cetak Risograph' },
            { value: 'sticker-style-with-white-outline', label: 'Gaya Stiker (outline putih)' },
            { value: 'geometric-art', label: 'Seni Geometris' },
        ]
    },
    {
        label: 'Media Tradisional',
        options: [
            { value: 'oil-painting-on-canvas', label: 'Lukisan Cat Minyak di Kanvas' },
            { value: 'watercolor-painting-soft', label: 'Lukisan Cat Air Lembut' },
            { value: 'gouache-on-textured-paper', label: 'Gouache di Kertas Bertekstur' },
            { value: 'pencil-sketch-textured', label: 'Sketsa Pensil Bertekstur' },
            { value: 'charcoal-drawing-smudged', label: 'Gambar Arang (Smudged)' },
            { value: 'ink-drawing-bold-lines', label: 'Gambar Tinta (Garis Tebal)' },
            { value: 'woodcut-print-style', label: 'Gaya Cetak Woodcut' },
            { value: 'colored-pencil-art', label: 'Seni Pensil Warna' },
            { value: 'chalk-drawing-on-blackboard', label: 'Gambar Kapur di Papan Tulis' },
            { value: 'ballpoint-pen-art', label: 'Seni Pulpen' },
        ]
    }
];

export const faceOptions: SelectOption[] = [
    { value: 'round', label: 'Bulat (Round)' },
    { value: 'round-youthful', label: 'Bulat (Muda & Imut)' },
    { value: 'oval', label: 'Oval' },
    { value: 'oval-adult-cute', label: 'Oval (Dewasa-imut)' },
    { value: 'oval-elegant', label: 'Oval (Elegan)' },
    { value: 'square', label: 'Kotak (Square)' },
    { value: 'square-strong-jaw', label: 'Kotak (Rahang tegas)' },
    { value: 'heart', label: 'Hati (Heart)' },
    { value: 'heart-sweet-chin', label: 'Hati (Dagu runcing & manis)' },
    { value: 'diamond', label: 'Berlian (Diamond)' },
    { value: 'oblong', label: 'Lonjong (Oblong)' },
    { value: 'triangular', label: 'Segitiga (Triangular)' },
    { value: 'soft-jawline', label: 'Garis Rahang Lembut' },
    { value: 'strong-jawline', label: 'Garis Rahang Tegas' },
    { value: 'chubby-cheeks', label: 'Pipi Tembem' },
    { value: 'defined-cheeks', label: 'Pipi Tirus' },
    { value: 'high-cheekbones', label: 'Tulang Pipi Tinggi' },
    { value: 'v-shaped-chin', label: 'Dagu Bentuk V' },
    { value: 'rounded-chin', label: 'Dagu Membulat' },
    { value: 'square-chin', label: 'Dagu Kotak' },
    { value: 'double-chin-subtle', label: 'Dagu Berlipat (Halus)' },
    { value: 'baby-face', label: 'Wajah Bayi (Baby Face)' },
    { value: 'mature-face-early-30s', label: 'Wajah Dewasa (Awal 30-an)' },
    { value: 'freckled-face', label: 'Wajah dengan Bintik (Freckles)' },
    { value: 'dimpled-cheeks', label: 'Pipi dengan Lesung Pipi' },
];

export const eyebrowOptions: SelectOption[] = [
    { value: 'thin-and-softly-arched', label: 'Tipis & melengkung lembut' },
    { value: 'thin-and-straight', label: 'Tipis & lurus' },
    { value: 'thin-and-high-arch', label: 'Tipis & lengkungan tinggi' },
    { value: 'natural-and-bushy', label: 'Alami & Lebat' },
    { value: 'natural-medium-thickness', label: 'Alami & Ketebalan Sedang' },
    { value: 'natural-softly-shaped', label: 'Alami & Bentuk Lembut' },
    { value: 'thick-and-arched', label: 'Tebal & Melengkung' },
    { value: 'thick-and-straight-korean-style', label: 'Tebal & Lurus (ala Korea)' },
    { value: 'thick-and-bold', label: 'Tebal & Tegas' },
    { value: 'soft-angled-arch', label: 'Lengkungan Sudut Lembut' },
    { value: 'sharp-angled-arch', label: 'Lengkungan Sudut Tajam' },
    { value: 'rounded-brows', label: 'Membulat' },
    { value: 'feathered-brows', label: 'Berserat (Feathered)' },
    { value: 'untamed-brows', label: 'Berantakan (Untamed)' },
    { value: 'high-arch-eyebrows', label: 'Lengkungan Tinggi' },
    { value: 'low-arch-eyebrows', label: 'Lengkungan Rendah' },
    { value: 'short-eyebrows', label: 'Alis Pendek' },
    { value: 'long-eyebrows', label: 'Alis Panjang' },
    { value: 'worried-brows-tilted-up', label: 'Alis Khawatir (Menaik)' },
    { value: 'angry-brows-tilted-down', label: 'Alis Marah (Menurun)' },
    { value: 'sad-brows-droopy', label: 'Alis Sedih (Terkulai)' },
    { value: 'surprised-brows-raised', label: 'Alis Terkejut (Terangkat)' },
    { value: 'colored-eyebrows-unnatural', label: 'Alis Berwarna (Tidak Natural)' },
    { value: 'caterpillar-brows', label: 'Alis Ulat' },
    { value: 'no-eyebrows', label: 'Tanpa Alis' },
];

export const eyesOptions: SelectOption[] = [
    { value: 'big-round-doe-eyes', label: 'Bulat Besar (Doe Eyes)' },
    { value: 'medium-round-eyes-brown-iris', label: 'Bulat Sedang (iris coklat)' },
    { value: 'small-round-eyes', label: 'Bulat Kecil' },
    { value: 'almond-shaped-eyes', label: 'Bentuk Almond' },
    { value: 'medium-oval-eyes-warm-brown-iris', label: 'Oval Sedang (iris coklat hangat)' },
    { value: 'narrow-eyes-black-iris', label: 'Sipit (iris hitam pekat)' },
    { value: 'upturned-cat-eyes', label: 'Mata Kucing (Upturned)' },
    { value: 'downturned-sad-eyes', label: 'Mata Sayu (Downturned)' },
    { value: 'hooded-eyes', label: 'Berkelopak (Hooded)' },
    { value: 'monolid-eyes', label: 'Monolid' },
    { value: 'double-eyelid-eyes', label: 'Kelopak Mata Ganda' },
    { value: 'bright-sparkling-eyes', label: 'Berbinar' },
    { value: 'deep-set-eyes', label: 'Mata Dalam (Deep-set)' },
    { value: 'wide-set-eyes', label: 'Mata Lebar (Jarak jauh)' },
    { value: 'close-set-eyes', label: 'Mata Dekat (Jarak dekat)' },
    { value: 'heterochromia-different-color-eyes', label: 'Heterochromia (Beda Warna)' },
    { value: 'dot-eyes-simple-cartoon', label: 'Mata Titik (Kartun Simple)' },
    { value: 'button-eyes-like-a-doll', label: 'Mata Kancing (Seperti Boneka)' },
    { value: 'long-eyelashes', label: 'Bulu Mata Lentik' },
    { value: 'anime-style-eyes-large-iris', label: 'Mata Gaya Anime (Iris Besar)' },
    { value: 'blue-iris', label: 'Iris Biru' },
    { value: 'green-iris', label: 'Iris Hijau' },
    { value: 'hazel-iris', label: 'Iris Hazel' },
    { value: 'grey-iris', label: 'Iris Abu-abu' },
    { value: 'eyes-with-bags-underneath-tired', label: 'Mata dengan Kantung Mata (Lelah)' },
];

export const lipsOptions: SelectOption[] = [
    { value: 'full-lips', label: 'Penuh' },
    { value: 'thin-lips', label: 'Tipis' },
    { value: 'cupids-bow-lips', label: 'Bentuk "Cupid\'s Bow"' },
    { value: 'heart-shaped-lips', label: 'Bentuk Hati' },
    { value: 'bow-shaped-lips', label: 'Bentuk Busur' },
    { value: 'heavy-lower-lip', label: 'Bibir Bawah Tebal' },
    { value: 'heavy-upper-lip', label: 'Bibir Atas Tebal' },
    { value: 'wide-lips', label: 'Lebar' },
    { value: 'narrow-lips', label: 'Sempit' },
    { value: 'subtle-smile-closed-mouth', label: 'Senyum tipis tertutup' },
    { value: 'natural-smile-closed-mouth', label: 'Senyum natural tanpa gigi' },
    { value: 'wide-smile-showing-teeth', label: 'Senyum lebar (terlihat gigi)' },
    { value: 'shy-smile', label: 'Senyum malu-malu' },
    { value: 'smirk', label: 'Seringai' },
    { value: 'pouting-lips', label: 'Mengerucut (Pouting)' },
    { value: 'downturned-lips-sad', label: 'Sedikit Cemberut (Sedih)' },
    { value: 'parted-lips-slightly-open', label: 'Sedikit terbuka' },
    { value: 'laughing-mouth-open', label: 'Tertawa (mulut terbuka)' },
    { value: 'surprised-o-shaped-mouth', label: 'Terkejut (mulut bentuk O)' },
    { value: 'whistling-lips', label: 'Bersiul' },
    { value: 'lipstick-colored-lips', label: 'Memakai Lipstik' },
    { value: 'glossy-lips', label: 'Mengkilap (Glossy)' },
    { value: 'matte-lips', label: 'Matte' },
    { value: 'defined-lipline', label: 'Garis Bibir Tegas' },
    { value: 'blurry-lipline-soft', label: 'Garis Bibir Samar (Soft)' },
];

export const noseOptions: SelectOption[] = [
    { value: 'small-button-nose', label: 'Kecil (Button)' },
    { value: 'small-asian-nose-low-bridge', label: 'Kecil Asia (batang rendah)' },
    { value: 'straight-nose', label: 'Lurus (dorsal lurus)' },
    { value: 'wide-nose', label: 'Lebar' },
    { value: 'narrow-nose', label: 'Ramping' },
    { value: 'upturned-nose', label: 'Mancung ke Atas' },
    { value: 'downturned-nose', label: 'Menukik ke Bawah' },
    { value: 'roman-nose', label: 'Romawi (Agak Besar)' },
    { value: 'aquiline-nose', label: 'Elang (Aquiline)' },
    { value: 'snub-nose', label: 'Pesek (Snub)' },
    { value: 'greek-nose-straight-bridge', label: 'Yunani (Pangkal Lurus)' },
    { value: 'hooked-nose', label: 'Bengkok (Hooked)' },
    { value: 'bulbous-nose', label: 'Ujung Membulat (Bulbous)' },
    { value: 'sharp-nose-tip', label: 'Ujung Tajam' },
    { value: 'flat-nose', label: 'Datar (Flat)' },
    { value: 'subtle-shading', label: 'Dengan shading halus' },
    { value: 'prominent-bridge', label: 'Pangkal Hidung Menonjol' },
    { value: 'wide-nostrils', label: 'Lubang Hidung Lebar' },
    { value: 'narrow-nostrils', label: 'Lubang Hidung Sempit' },
    { value: 'cute-cartoon-triangle-nose', label: 'Segitiga (Gaya Kartun Lucu)' },
    { value: 'simple-line-for-nose', label: 'Hanya Garis Sederhana' },
    { value: 'no-nose-cartoon-style', label: 'Tanpa Hidung (Gaya Kartun)' },
    { value: 'red-nose-tip-like-rudolph', label: 'Ujung Hidung Merah' },
    { value: 'nose-with-plaster-bandage', label: 'Hidung dengan Plester' },
    { value: 'nose-wrinkle-when-smiling', label: 'Kerutan saat tersenyum' },
];

export const hairHijabOptions: OptionGroup[] = [
    { label: 'Rambut', options: [
        { value: 'bald', label: 'Botak' },
        { value: 'buzz-cut', label: 'Cepak (Buzz Cut)' },
        { value: 'short-pixie-hair', label: 'Pendek (Pixie)' },
        { value: 'short-messy-hair', label: 'Pendek Berantakan' },
        { value: 'spiky-hair', label: 'Spiky' },
        { value: 'undercut-hair', label: 'Undercut' },
        { value: 'mohawk', label: 'Mohawk' },
        { value: 'bowl-cut', label: 'Potongan Mangkuk' },
        { value: 'medium-bob-hair', label: 'Sebahu (Bob)' },
        { value: 'layered-bob', label: 'Bob Layer' },
        { value: 'shaggy-hair', label: 'Shaggy' },
        { value: 'ponytail-high', label: 'Kuncir Kuda (Tinggi)' },
        { value: 'ponytail-low', label: 'Kuncir Kuda (Rendah)' },
        { value: 'twin-tails', label: 'Kuncir Dua' },
        { value: 'pigtails', label: 'Kuncir Kepang Dua' },
        { value: 'bun-hair-top-knot', label: 'Cepol Atas (Top Knot)' },
        { value: 'messy-bun', label: 'Cepol Berantakan' },
        { value: 'space-buns', label: 'Cepol Dua (Space Buns)' },
        { value: 'long-straight-hair', label: 'Panjang Lurus' },
        { value: 'long-wavy-hair', label: 'Panjang Ikal' },
        { value: 'long-curly-hair', label: 'Panjang Keriting' },
        { value: 'braids-single', label: 'Kepang Satu' },
        { value: 'french-braid', label: 'Kepang Perancis' },
        { value: 'dutch-braids', label: 'Kepang Belanda' },
        { value: 'dreadlocks', label: 'Dreadlocks' },
        { value: 'cornrows', label: 'Cornrows' },
        { value: 'curly-afro-hair', label: 'Keriting Afro' },
        { value: 'side-swept-bangs', label: 'Poni Samping' },
        { value: 'blunt-bangs', label: 'Poni Rata' },
        { value: 'curtain-bangs', label: 'Poni Tirai' },
    ]},
    { label: 'Hijab', options: [
        { value: 'simple-syari-hijab', label: 'Simple Syar\'i' },
        { value: 'pashmina-style-hijab', label: 'Gaya Pashmina' },
        { value: 'pashmina-wrapped-neatly', label: 'Pashmina dililit rapi' },
        { value: 'square-hijab-folded-neatly', label: 'Hijab Segi Empat (dilipat rapi)' },
        { value: 'turban-style-hijab', label: 'Gaya Turban' },
        { value: 'sporty-hijab', label: 'Hijab Sporty' },
        { value: 'khimar-hijab-long', label: 'Khimar (Panjang)' },
        { value: 'bergo-hijab-instant', label: 'Bergo (Instan)' },
        { value: 'niqab-style', label: 'Gaya Niqab' },
        { value: 'layered-hijab-style', label: 'Gaya Hijab Layer' },
        { value: 'hijab-with-inner-cap-visible', label: 'Hijab dengan Ciput (terlihat)' },
        { value: 'flowy-hijab', label: 'Hijab Menjuntai (Flowy)' },
        { value: 'hijab-with-accessories-pins', label: 'Hijab dengan Aksesoris (Jarum)' },
    ]}
];

export const accessoriesOptions: (OptionGroup | SelectOption)[] = [
    { label: 'Kepala & Wajah', options: [
        { value: 'thin-round-glasses', label: 'Kacamata bulat bingkai tipis' },
        { value: 'square-nerd-glasses', label: 'Kacamata kotak (nerd-style)' },
        { value: 'cat-eye-glasses', label: 'Kacamata Cat-eye' },
        { value: 'aviator-sunglasses', label: 'Kacamata Hitam Aviator' },
        { value: 'wayfarer-sunglasses', label: 'Kacamata Hitam Wayfarer' },
        { value: 'headband', label: 'Bando' },
        { value: 'beanie', label: 'Kupluk (Beanie)' },
        { value: 'snapback-cap', label: 'Topi Snapback' },
        { value: 'fedora-hat', label: 'Topi Fedora' },
        { value: 'bucket-hat', label: 'Topi Bucket' },
        { value: 'baseball-cap', label: 'Topi Baseball' },
        { value: 'headphones-on-head', label: 'Headphone di kepala' },
        { value: 'headphones-around-neck', label: 'Headphone di leher' },
        { value: 'earpods-or-earbuds', label: 'Earpods atau Earbuds' },
        { value: 'tiara-or-crown', label: 'Tiara atau Mahkota' },
        { value: 'flower-crown', label: 'Mahkota Bunga' },
        { value: 'face-mask', label: 'Masker Wajah' },
        { value: 'nose-ring', label: 'Tindik Hidung' },
        { value: 'lip-ring', label: 'Tindik Bibir' },
        { value: 'freckles-added', label: 'Bintik-bintik (Freckles)' },
        { value: 'mole-beauty-mark', label: 'Tahi Lalat' },
        { value: 'earrings-stud', label: 'Anting (Tusuk)' },
        { value: 'hoop-earrings', label: 'Anting Bundar' },
        { value: 'dangling-earrings', label: 'Anting Gantung' },
        { value: 'bandana-on-head', label: 'Bandana di Kepala' },
    ]},
    { label: 'Leher & Badan', options: [
        { value: 'simple-necklace', label: 'Kalung Simple' },
        { value: 'pendant-necklace', label: 'Kalung Liontin' },
        { value: 'choker', label: 'Choker' },
        { value: 'scarf', label: 'Syal' },
        { value: 'necktie', label: 'Dasi' },
        { value: 'bow-tie', label: 'Dasi Kupu-kupu' },
        { value: 'brooch', label: 'Bros' },
        { value: 'belt-leather', label: 'Ikat Pinggang Kulit' },
        { value: 'sash', label: 'Selempang' },
        { value: 'camera-around-neck', label: 'Kamera menggantung di leher' },
        { value: 'id-card-lanyard', label: 'Tali ID Card' },
    ]},
     { label: 'Tangan & Lengan', options: [
        { value: 'digital-watch', label: 'Jam Tangan Digital' },
        { value: 'analog-watch', label: 'Jam Tangan Analog' },
        { value: 'smartwatch', label: 'Smartwatch' },
        { value: 'friendship-bracelet', label: 'Gelang Persahabatan' },
        { value: 'leather-bracelet', label: 'Gelang Kulit' },
        { value: 'rings-on-fingers', label: 'Cincin di jari' },
        { value: 'fingerless-gloves', label: 'Sarung Tangan Tanpa Jari' },
        { value: 'arm-warmers', label: 'Penghangat Lengan' },
        { value: 'temporary-tattoo-on-arm', label: 'Tato temporer di lengan' },
    ]},
     { label: 'Tas', options: [
        { value: 'backpack', label: 'Tas Ransel' },
        { value: 'sling-bag', label: 'Tas Selempang' },
        { value: 'tote-bag', label: 'Tote Bag' },
        { value: 'handbag', label: 'Tas Tangan' },
        { value: 'clutch-bag', label: 'Tas Genggam (Clutch)' },
        { value: 'fanny-pack', label: 'Tas Pinggang' },
    ]},
    { value: 'no-accessories', label: 'Tanpa Aksesoris' }
];

export const outfitOptions: OptionGroup[] = [
    {
        label: 'Gaya Kasual & Sehari-hari',
        options: [
            { value: 'everyday-casual', label: 'Kasual Sehari-hari (Jeans & Kaos)' },
            { value: 'athleisure-sporty', label: 'Athleisure (Sporty & Nyaman)' },
            { value: 'streetwear-urban', label: 'Streetwear (Urban & Hype)' },
            { value: 'bohemian-chic', label: 'Bohemian (Artistik & Bebas)' },
            { value: 'preppy-classic', label: 'Preppy (Klasik & Rapi)' },
            { value: 'soft-girl-boy', label: 'Soft Girl/Boy (Pastel & Imut)' },
            { value: 'e-girl-boy', label: 'E-Girl/E-Boy (Internet Culture)' },
            { value: 'skater-style', label: 'Gaya Skater (Longgar & Keren)' },
            { value: 'normcore-simple', label: 'Normcore (Sederhana & Anti-Fashion)' },
            { value: 'loungewear-cozy', label: 'Loungewear (Pakaian Santai di Rumah)' },
        ]
    },
    {
        label: 'Gaya Profesional & Formal',
        options: [
            { value: 'business-formal', label: 'Bisnis Formal (Setelan Jas)' },
            { value: 'business-casual', label: 'Bisnis Kasual (Kemeja & Celana Kain)' },
            { value: 'smart-casual', label: 'Smart Casual (Blazer & Jeans)' },
            { value: 'elegant-minimalist', label: 'Minimalis Elegan' },
            { value: 'dark-academia', label: 'Dark Academia (Intelektual & Vintage)' },
            { value: 'light-academia', label: 'Light Academia (Klasik & Cerah)' },
            { value: 'cocktail-attire', label: 'Pakaian Cocktail (Semi-Formal)' },
            { value: 'formal-gala-dress', label: 'Gaun Gala Formal' },
        ]
    },
    {
        label: 'Gaya Modern & Urban',
        options: [
            { value: 'techwear-functional', label: 'Techwear (Fungsional & Futuristik)' },
            { value: 'monochrome-style', label: 'Gaya Monokrom' },
            { value: 'avant-garde-experimental', label: 'Avant-garde (Eksperimental)' },
            { value: 'futuristic-minimalist', label: 'Futuristik Minimalis' },
            { value: 'urban-explorer', label: 'Penjelajah Kota (Urban Explorer)' },
            { value: 'cyberpunk-neon', label: 'Cyberpunk (Neon & High-tech)' },
        ]
    },
    {
        label: 'Gaya Vintage & Alternatif',
        options: [
            { value: 'grunge-90s-alternative', label: 'Grunge (Alternatif 90-an)' },
            { value: 'punk-rock', label: 'Punk Rock' },
            { value: 'gothic-style', label: 'Gothic (Gelap & Dramatis)' },
            { value: 'steampunk-victorian-tech', label: 'Steampunk (Victoria & Mesin)' },
            { value: 'retro-70s-style', label: 'Retro Gaya 70-an' },
            { value: 'vintage-50s-diner-style', label: 'Vintage Gaya 50-an' },
            { value: 'hippie-60s-style', label: 'Hippie Gaya 60-an' },
            { value: 'y2k-early-2000s', label: 'Y2K (Awal 2000-an)' },
            { value: 'cottagecore-romantic-rural', label: 'Cottagecore (Pedesaan Romantis)' },
            { value: 'fairycore-ethereal', label: 'Fairycore (Ethereal & Magis)' },
        ]
    },
    {
        label: 'Gaya Tematik & Fantasi',
        options: [
            { value: 'fantasy-adventurer', label: 'Petualang Fantasi' },
            { value: 'mage-or-wizard-robes', label: 'Jubah Penyihir' },
            { value: 'sci-fi-warrior-armor', label: 'Baju Zirah Pejuang Sci-Fi' },
            { value: 'royal-prince-princess', label: 'Pakaian Kerajaan' },
            { value: 'pirate-outfit', label: 'Pakaian Bajak Laut' },
            { value: 'anime-school-uniform', label: 'Seragam Sekolah Anime' },
            { value: 'k-pop-idol-stage-outfit', label: 'Pakaian Panggung Idol K-Pop' },
            { value: 'magical-girl-outfit', label: 'Pakaian Magical Girl' },
            { value: 'post-apocalyptic-survivor', label: 'Pakaian Penyintas Pasca-kiamat' },
            { value: 'superhero-costume', label: 'Kostum Superhero' },
        ]
    },
    {
        label: 'Gaya Budaya (Modern)',
        options: [
            { value: 'modern-batik-wear', label: 'Pakaian Batik Modern' },
            { value: 'modern-kebaya', label: 'Kebaya Modern' },
            { value: 'modern-kimono-style', label: 'Gaya Kimono Modern' },
            { value: 'modern-hanbok-style', label: 'Gaya Hanbok Modern' },
        ]
    }
];

export const lightingOptions: SelectOption[] = [
    { value: 'soft-studio-lighting', label: 'Studio (Soft)' },
    { value: 'three-point-lighting', label: 'Studio (Three-point)' },
    { value: 'butterfly-lighting', label: 'Pencahayaan Butterfly (Glamour)' },
    { value: 'rembrandt-lighting', label: 'Pencahayaan Rembrandt (Dramatis)' },
    { value: 'dramatic-cinematic-lighting', label: 'Sinematik (Dramatis)' },
    { value: 'hard-shadow-film-noir', label: 'Bayangan Keras (Film Noir)' },
    { value: 'natural-sunlight-bright', label: 'Cahaya Matahari Alami (Terang)' },
    { value: 'overcast-daylight-soft-shadows', label: 'Cahaya Siang Mendung (Bayangan Lembut)' },
    { value: 'golden-hour-light-warm', label: 'Cahaya Golden Hour (Hangat)' },
    { value: 'blue-hour-light-cool', label: 'Cahaya Blue Hour (Dingin)' },
    { value: 'moonlight', label: 'Cahaya Bulan' },
    { value: 'backlight-creating-silhouette', label: 'Siluet (Cahaya dari Belakang)' },
    { value: 'rim-lighting-edge-highlight', label: 'Cahaya Pinggir (Rim Light)' },
    { value: 'neon-glow-from-signs', label: 'Cahaya Neon dari Papan Iklan' },
    { value: 'cyberpunk-neon-lighting', label: 'Pencahayaan Neon Cyberpunk' },
    { value: 'candlelight-flickering', label: 'Cahaya Lilin (Berkedip)' },
    { value: 'campfire-light', label: 'Cahaya Api Unggun' },
    { value: 'under-lighting-spooky', label: 'Cahaya dari Bawah (Misterius)' },
    { value: 'dappled-light-through-leaves', label: 'Cahaya belang-belang (dari daun)' },
    { value: 'volumetric-light-beams', label: 'Sinar Cahaya Volumetrik' },
    { value: 'glowing-magical-aura', label: 'Aura Magis Bercahaya' },
    { value: 'stage-spotlight', label: 'Lampu Sorot Panggung' },
    { value: 'underwater-light-caustics', label: 'Cahaya Bawah Air (Kaustik)' },
    { value: 'low-key-lighting-dark', label: 'Pencahayaan Low-key (Gelap)' },
    { value: 'high-key-lighting-bright', label: 'Pencahayaan High-key (Terang)' },
];

export const poseOptions: OptionGroup[] = [
    {
        label: 'Gaya & Emosi',
        options: [
            { value: 'happy-and-smiling-brightly', label: 'Senang dan tersenyum cerah' },
            { value: 'gentle-smile', label: 'Senyum lembut' },
            { value: 'grateful-smile-hands-on-heart', label: 'Senyum berterima kasih (tangan di dada)'},
            { value: 'wide-grinning-smile', label: 'Senyum lebar menyeringai' },
            { value: 'smirking-mischievously', label: 'Seringai nakal' },
            { value: 'smug-look-arms-crossed', label: 'Tampak sombong (tangan bersedekap)'},
            { value: 'sarcastic-smile', label: 'Senyum sarkastis'},
            { value: 'laughing-out-loud', label: 'Tertawa terbahak-bahak' },
            { value: 'pouting-playfully', label: 'Cemberut main-main' },
            { value: 'grumpy-pout', label: 'Cemberut kesal'},
            { value: 'sticking-tongue-out-playfully', label: 'Menjulurkan lidah (main-main)' },
            { value: 'winking-one-eye', label: 'Mengedipkan satu mata' },
            { value: 'mischievous-wink', label: 'Kedipan mata nakal' },
            { value: 'flirty-wink-and-smile', label: 'Kedipan genit dan senyum'},
            { value: 'blowing-a-kiss-playfully', label: 'Meniup ciuman (main-main)' },
            { value: 'confident-stance-hands-on-hips', label: 'Pose percaya diri (tangan di pinggul)' },
            { value: 'feeling-proud-chest-out', label: 'Merasa bangga (dada membusung)' },
            { value: 'proud-and-satisfied-smile', label: 'Senyum bangga dan puas' },
            { value: 'triumphant-roar', label: 'Mengaum kemenangan'},
            { value: 'fierce-battle-cry', label: 'Teriakan perang yang garang'},
            { value: 'determined-look-focused-eyes', label: 'Tatapan penuh tekad (fokus)' },
            { value: 'arms-crossed-confidently', label: 'Tangan bersedekap (percaya diri)' },
            { value: 'thinking-pose-chin-on-hand', label: 'Pose berpikir (dagu di tangan)' },
            { value: 'contemplative-look-stroking-chin', label: 'Tampak merenung (mengelus dagu)'},
            { value: 'pensive-look-gazing-into-distance', label: 'Tampak merenung (melihat ke kejauhan)' },
            { value: 'thoughtful-and-introspective', label: 'Tampak berpikir dan introspektif' },
            { value: 'daydreaming-look-staring-into-space', label: 'Melamun (menatap ke angkasa)'},
            { value: 'curious-look-head-tilted', label: 'Ekspresi penasaran (kepala miring)' },
            { value: 'suspicious-squint', label: 'Menyipitkan mata curiga'},
            { value: 'surprised-expression-mouth-open', label: 'Ekspresi terkejut (mulut terbuka)' },
            { value: 'excited-gasp-hands-on-cheeks', label: 'Terkesiap gembira (tangan di pipi)'},
            { value: 'eyes-wide-with-awe', label: 'Mata terbelalak kagum' },
            { value: 'shy-pose-looking-down', label: 'Pose malu (melihat ke bawah)' },
            { value: 'embarrassed-blush-covering-face', label: 'Malu merona (menutupi wajah)'},
            { value: 'innocent-look-big-puppy-eyes', label: 'Tampak polos (mata memelas)'},
            { value: 'nervous-smile-fiddling-with-hands', label: 'Senyum gugup (memainkan tangan)'},
            { value: 'scared-expression', label: 'Ekspresi takut' },
            { value: 'angry-glare', label: 'Tatapan marah' },
            { value: 'rolling-eyes-in-annoyance', label: 'Memutar mata (kesal)' },
            { value: 'bored-expression-leaning-on-hand', label: 'Ekspresi bosan (bersandar di tangan)'},
            { value: 'sleepy-yawn', label: 'Menguap ngantuk' },
            { value: 'tired-sigh', label: 'Menghela napas lelah'},
            { value: 'relieved-sigh', label: 'Menghela napas lega'},
            { value: 'crying-with-joy', label: 'Menangis bahagia' },
            { value: 'overwhelmed-expression-head-in-hands', label: 'Ekspresi kewalahan (kepala di tangan)'},
            { value: 'facepalming-in-disbelief', label: 'Menepuk dahi (tidak percaya)' },
            { value: 'shrugging-shoulders-quizzically', label: 'Mengangkat bahu (bingung)' },
            { value: 'nodding-in-agreement', label: 'Mengangguk setuju'},
            { value: 'shaking-head-in-disagreement', label: 'Menggeleng tidak setuju'},
            { value: 'shushing-gesture-finger-to-lips', label: 'Gestur diam (jari di bibir)'},
            { value: 'whispering-a-secret', label: 'Membisikkan rahasia'},
            { value: 'celebrating-with-fist-pump', label: 'Merayakan dengan kepalan tangan' },
            { value: 'praying-hands-serenely', label: 'Tangan berdoa (tenang)' },
            { value: 'serene-and-peaceful-expression', label: 'Ekspresi tenang dan damai' },
        ],
    },
    {
        label: 'Interaksi & Produk',
        options: [
            { value: 'holding-product-in-right-hand', label: 'Memegang produk di tangan kanan' },
            { value: 'holding-product-in-left-hand', label: 'Memegang produk di tangan kiri' },
            { value: 'presenting-product-with-both-hands', label: 'Menyajikan produk dengan dua tangan' },
            { value: 'pointing-to-product-on-the-right', label: 'Menunjuk produk di sebelah kanan' },
            { value: 'pointing-to-product-on-the-left', label: 'Menunjuk produk di sebelah kiri' },
            { value: 'pointing-up-to-product-above', label: 'Menunjuk produk di atas' },
            { value: 'pointing-down-to-product-below', label: 'Menunjuk produk di bawah' },
            { value: 'right-hand-thumbs-up-left-hand-presenting-product', label: 'Tangan kanan jempol, tangan kiri menyajikan produk' },
            { value: 'left-hand-thumbs-up-right-hand-presenting-product', label: 'Tangan kiri jempol, tangan kanan menyajikan produk' },
            { value: 'holding-a-book', label: 'Memegang buku' },
            { value: 'holding-a-cup-of-coffee', label: 'Memegang cangkir kopi' },
            { value: 'holding-a-phone', label: 'Memegang ponsel' },
            { value: 'holding-a-tablet', label: 'Memegang tablet' },
            { value: 'typing-on-a-laptop', label: 'Mengetik di laptop' },
            { value: 'writing-in-a-notebook', label: 'Menulis di buku catatan' },
            { value: 'holding-a-shopping-bag', label: 'Membawa tas belanja' },
            { value: 'unboxing-a-product', label: 'Membuka kotak produk' },
            { value: 'shaking-hands-with-someone', label: 'Berjabat tangan' },
            { value: 'giving-a-gift', label: 'Memberikan hadiah' },
            { value: 'hugging-a-plush-toy', label: 'Memeluk boneka' },
            { value: 'pointing-at-a-chart', label: 'Menunjuk ke grafik' },
            { value: 'holding-a-trophy', label: 'Memegang piala' },
            { value: 'serving-food-on-a-platter', label: 'Menyajikan makanan di nampan' },
            { value: 'using-a-VR-headset', label: 'Menggunakan headset VR'},
            { value: 'holding-a-game-controller', label: 'Memegang kontroler game'},
            { value: 'applying-makeup', label: 'Mengaplikasikan riasan'},
            { value: 'smelling-a-flower', label: 'Mencium bunga'},
            { value: 'arranging-flowers-in-a-vase', label: 'Merangkai bunga di vas'},
        ],
    },
    {
        label: 'Aksi & Gerakan',
        options: [
            { value: 'walking-forward', label: 'Berjalan ke depan' },
            { value: 'running-energetically', label: 'Berlari penuh semangat' },
            { value: 'jumping-with-joy', label: 'Melompat gembira' },
            { value: 'dancing-freely', label: 'Menari bebas' },
            { value: 'twirling-around', label: 'Berputar-putar'},
            { value: 'waving-hello-cheerfully', label: 'Melambai (halo) dengan ceria' },
            { value: 'clapping-hands-enthusiastically', label: 'Tepuk tangan dengan antusias' },
            { value: 'stretching-arms-upward', label: 'Meregangkan tangan ke atas' },
            { value: 'taking-a-step-forward', label: 'Melangkah ke depan' },
            { value: 'leaning-forward-with-interest', label: 'Mencondongkan badan ke depan (tertarik)' },
            { value: 'tiptoeing-sneakily', label: 'Berjingkat (mengendap-endap)' },
            { value: 'cartwheeling', label: 'Melakukan cartwheel/meroda' },
            { value: 'doing-a-handstand', label: 'Melakukan handstand' },
            { value: 'doing-a-backflip', label: 'Melakukan backflip/salto'},
            { value: 'moonwalking', label: 'Melakukan moonwalk'},
            { value: 'marching', label: 'Berbaris'},
            { value: 'sliding-down-a-rail', label: 'Meluncur di pegangan tangga' },
            { value: 'swinging-on-a-swing', label: 'Bermain ayunan' },
            { value: 'skipping-happily', label: 'Melompat-lompat kecil (skipping)' },
        ],
    },
    {
        label: 'Berdiri & Presentasi',
        options: [
            { value: 'standing-straight-at-attention', label: 'Berdiri tegak' },
            { value: 'standing-casually-one-leg-bent', label: 'Berdiri santai (satu kaki ditekuk)' },
            { value: 'leaning-against-a-wall-cooly', label: 'Bersandar di dinding (keren)' },
            { value: 'presenting-to-the-side-open-palm', label: 'Mempresentasikan ke samping (telapak terbuka)' },
            { value: 'giving-a-speech-at-a-podium', label: 'Berpidato di podium' },
            { value: 'hands-in-pockets-casually', label: 'Tangan di dalam saku (santai)' },
            { value: 'welcoming-gesture-with-open-arms', label: 'Gestur menyambut (tangan terbuka lebar)' },
            { value: 'bowing-respectfully', label: 'Membungkuk hormat' },
            { value: 'taking-a-bow', label: 'Memberi hormat (setelah pertunjukan)'},
            { value: 'pointing-at-the-viewer', label: 'Menunjuk ke arah penonton' },
            { value: 'holding-microphone-and-speaking', label: 'Memegang mikrofon dan berbicara' },
            { value: 'explaining-on-a-whiteboard', label: 'Menjelaskan di papan tulis' },
            { value: 'waving-a-flag', label: 'Mengibarkan bendera'},
            { value: 'directing-traffic', label: 'Mengarahkan lalu lintas'},
        ],
    },
    {
        label: 'Duduk & Santai',
        options: [
            { value: 'sitting-on-a-chair-attentively', label: 'Duduk di kursi (penuh perhatian)' },
            { value: 'sitting-on-the-floor-cross-legged', label: 'Duduk bersila di lantai' },
            { value: 'sitting-on-a-stool', label: 'Duduk di bangku kecil' },
            { value: 'reading-a-book-while-sitting', label: 'Duduk sambil membaca buku' },
            { value: 'meditating-pose-calmly', label: 'Pose meditasi (tenang)' },
            { value: 'relaxing-on-a-sofa', label: 'Bersantai di sofa' },
            { value: 'kneeling-on-one-knee', label: 'Berlutut dengan satu kaki' },
            { value: 'sitting-at-a-desk', label: 'Duduk di meja kerja' },
            { value: 'lounging-on-a-beanbag', label: 'Bersantai di beanbag' },
            { value: 'picnic-pose-on-a-blanket', label: 'Pose piknik di atas selimut' },
        ],
    },
    {
        label: 'Hobi & Profesi',
        options: [
            { value: 'painting-on-a-canvas', label: 'Melukis di kanvas' },
            { value: 'playing-guitar', label: 'Bermain gitar' },
            { value: 'cooking-in-the-kitchen', label: 'Memasak di dapur' },
            { value: 'gardening-with-tools', label: 'Berkebun dengan peralatan' },
            { value: 'taking-a-photo-with-a-camera', label: 'Mengambil foto dengan kamera' },
            { value: 'doctor-with-stethoscope', label: 'Dokter dengan stetoskop' },
            { value: 'teacher-writing-on-a-board', label: 'Guru menulis di papan tulis' },
            { value: 'scientist-holding-a-beaker', label: 'Ilmuwan memegang gelas kimia' },
            { value: 'programmer-coding-on-computer', label: 'Programmer mengetik kode' },
            { value: 'chef-tasting-food', label: 'Koki mencicipi makanan' },
            { value: 'musician-playing-piano', label: 'Musisi bermain piano' },
            { value: 'artist-sketching-in-a-pad', label: 'Seniman membuat sketsa' },
            { value: 'barista-making-coffee', label: 'Barista membuat kopi' },
            { value: 'DJ-at-turntables', label: 'DJ di meja putar' },
            { value: 'conducting-an-orchestra', label: 'Memimpin orkestra' },
            { value: 'baking-cookies', label: 'Membuat kue kering' },
            { value: 'building-with-blocks', label: 'Membangun dengan balok' },
            { value: 'pilot-in-cockpit', label: 'Pilot di kokpit' },
            { value: 'firefighter-holding-a-hose', label: 'Pemadam kebakaran memegang selang' },
            { value: 'pottery-on-a-wheel', label: 'Membuat tembikar'},
            { value: 'knitting-or-crocheting', label: 'Merajut atau merenda'},
            { value: 'playing-chess', label: 'Bermain catur'},
        ],
    },
     {
        label: 'Olahraga & Kebugaran',
        options: [
            { value: 'yoga-warrior-pose', label: 'Pose Yoga (Warrior)' },
            { value: 'lifting-dumbbells', label: 'Mengangkat barbel' },
            { value: 'dribbling-a-basketball', label: 'Menggiring bola basket' },
            { value: 'kicking-a-soccer-ball', label: 'Menendang bola' },
            { value: 'jogging-in-place', label: 'Jogging di tempat' },
            { value: 'riding-a-bicycle', label: 'Mengendarai sepeda' },
            { value: 'swimming-freestyle', label: 'Berenang gaya bebas' },
            { value: 'hitting-a-tennis-ball', label: 'Memukul bola tenis' },
            { value: 'doing-push-ups', label: 'Push-up' },
            { value: 'holding-a-plank-pose', label: 'Pose plank' },
            { value: 'surfing-on-a-wave', label: 'Berselancar di ombak'},
            { value: 'skateboarding', label: 'Bermain skateboard'},
        ],
    },
    {
        label: 'Konsep & Ide',
        options: [
            { value: 'holding-a-lightbulb-idea', label: 'Memegang bola lampu (ide)' },
            { value: 'looking-up-with-inspiration', label: 'Melihat ke atas (inspirasi)' },
            { value: 'connecting-dots-in-the-air', label: 'Menghubungkan titik di udara' },
            { value: 'balancing-on-one-foot', label: 'Menjaga keseimbangan dengan satu kaki' },
            { value: 'holding-a-growing-plant', label: 'Memegang tanaman yang tumbuh' },
            { value: 'shouting-through-a-megaphone', label: 'Berteriak dengan megafon' },
            { value: 'juggling-ideas', label: 'Juggling ide (konseptual)' },
            { value: 'holding-a-key', label: 'Memegang kunci (solusi)' },
        ],
    },
    {
        label: 'Selfie & Vlogging',
        options: [
            { value: 'selfie-smiling-at-camera', label: 'Selfie tersenyum ke kamera' },
            { value: 'selfie-with-peace-sign', label: 'Selfie dengan tanda peace' },
            { value: 'selfie-duck-face', label: 'Selfie dengan duck face' },
            { value: 'selfie-from-high-angle', label: 'Selfie dari angle atas' },
            { value: 'winking-selfie', label: 'Selfie sambil mengedipkan mata' },
            { value: 'holding-camera-vlogging-style', label: 'Memegang kamera (gaya vlogging)' },
            { value: 'group-selfie-pose', label: 'Pose selfie grup' },
            { value: 'selfie-showing-off-food', label: 'Selfie memamerkan makanan' },
        ]
    },
    {
        label: 'Spesifik & Kreatif',
        options: [
            { value: 'making-a-heart-shape-with-hands', label: 'Membuat bentuk hati dengan tangan' },
            { value: 'making-a-finger-heart', label: 'Membuat hati dengan jari (finger heart)'},
            { value: 'peace-sign-with-one-hand', label: 'Tanda peace dengan satu tangan' },
            { value: 'peace-sign-with-both-hands', label: 'Tanda peace dengan kedua tangan' },
            { value: 'finger-gun-pose', label: 'Pose pistol jari' },
            { value: 'live-long-and-prosper-sign', label: 'Salam Vulcan (live long and prosper)'},
            { value: 'call-me-hand-gesture', label: 'Gestur tangan "telepon aku"'},
            { value: 'counting-on-fingers', label: 'Menghitung dengan jari'},
            { value: 'creating-a-frame-with-hands', label: 'Membuat bingkai dengan tangan'},
            { value: 'holding-a-blank-sign', label: 'Memegang papan kosong' },
            { value: 'looking-through-binoculars', label: 'Melihat melalui teropong' },
            { value: 'holding-a-magnifying-glass', label: 'Memegang kaca pembesar' },
            { value: 'superhero-pose-on-a-rooftop', label: 'Pose pahlawan super di atap' },
            { value: 'peeking-from-behind-a-wall', label: 'Mengintip dari balik dinding' },
            { value: 'juggling-items', label: 'Juggling berbagai benda' },
            { value: 'saluting-formally', label: 'Memberi hormat (formal)' },
            { value: 'checking-the-time-on-a-watch', label: 'Melihat jam tangan' },
            { value: 'giving-a-high-five', label: 'Melakukan tos' },
            { value: 'holding-an-umbrella', label: 'Memegang payung' },
            { value: 'meditating-in-lotus-position', label: 'Meditasi posisi lotus' },
            { value: 'looking-through-a-keyhole', label: 'Mengintip dari lubang kunci' },
            { value: 'hiding-face-behind-hands', label: 'Menyembunyikan wajah di balik tangan' },
            { value: 'leaning-out-a-window', label: 'Melongok ke luar jendela' },
        ],
    },
];


export const angleOptions: OptionGroup[] = [
    {
        label: 'Ketinggian & Sudut Vertikal',
        options: [
            { value: 'low-angle', label: 'Sudut Rendah (Low-angle)' },
            { value: 'high-angle', label: 'Sudut Tinggi (High-angle)' },
            { value: 'eye-level', label: 'Sejajar Mata (Eye-level)' },
            { value: 'extreme-low-angle', label: 'Sudut Sangat Rendah (Extreme Low-angle)' },
            { value: 'subtle-low-angle', label: 'Sudut Rendah Halus (Subtle)' },
            { value: 'subtle-high-angle', label: 'Sudut Tinggi Halus (Subtle)' },
            { value: 'birds-eye-view', label: 'Tampak Atas (Bird\'s-eye)' },
            { value: 'worms-eye-view', label: 'Tampak dari Bawah (Worm\'s-eye)' },
            { value: 'top-down-shot', label: 'Tampak Lurus dari Atas (Top-down)' },
            { value: 'ground-level-shot', label: 'Sejajar Tanah (Ground-level)' },
            { value: 'knee-level-shot', label: 'Sejajar Lutut (Knee-level)' },
            { value: 'hip-level-shot', label: 'Sejajar Pinggul (Hip-level)' },
            { value: 'hero-shot', label: 'Hero Shot (Sudut Rendah Dramatis)' },
            { value: 'villain-shot', label: 'Villain Shot (Sudut Tinggi Mengancam)' },
        ]
    },
    {
        label: 'Framing & Jarak',
        options: [
            { value: 'establishing-shot', label: 'Establishing Shot (Pengenalan Lokasi)' },
            { value: 'master-shot', label: 'Master Shot (Seluruh Adegan)' },
            { value: 'wide-shot', label: 'Wide Shot (Sangat Luas)' },
            { value: 'long-shot', label: 'Long Shot (Karakter & Lingkungan)' },
            { value: 'full-shot', label: 'Full Shot (Seluruh badan)' },
            { value: 'medium-full-shot', label: 'Medium Full Shot (Lutut ke atas)' },
            { value: 'cowboy-shot', label: 'Cowboy Shot (Paha ke atas)' },
            { value: 'medium-shot', label: 'Medium Shot (Pinggang ke atas)' },
            { value: 'medium-close-up', label: 'Medium Close-up (Dada ke atas)' },
            { value: 'close-up', label: 'Close-up (Kepala & Bahu)' },
            { value: 'extreme-close-up', label: 'Extreme Close-up (Hanya Wajah)' },
            { value: 'insert-shot', label: 'Insert Shot (Detail Objek)' },
            { value: 'two-shot', label: 'Two Shot (Dua Karakter)' },
        ]
    },
    {
        label: 'Arah & Perspektif',
        options: [
            { value: 'front-view', label: 'Tampak Depan (Menghadap Kamera)' },
            { value: 'looking-at-camera', label: 'Melihat lurus ke kamera' },
            { value: 'breaking-the-fourth-wall', label: 'Menatap langsung (Breaking the 4th Wall)' },
            { value: 'three-quarter-view', label: 'Tampak 3/4 dari Depan' },
            { value: 'profile-shot-left', label: 'Tampak Samping Kiri (Profil)' },
            { value: 'profile-shot-right', label: 'Tampak Samping Kanan (Profil)' },
            { value: 'three-quarter-rear-view', label: 'Tampak 3/4 dari Belakang' },
            { value: 'rear-view', label: 'Tampak dari Belakang' },
            { value: 'over-the-shoulder-shot', label: 'Dari Atas Bahu' },
            { value: 'looking-over-shoulder-at-camera', label: 'Melihat ke kamera dari balik bahu' },
            { value: 'glancing-back-at-camera', label: 'Melirik ke belakang ke arah kamera' },
            { value: 'looking-away-from-camera', label: 'Melihat ke Samping (Tidak ke kamera)' },
            { value: 'looking-up', label: 'Melihat ke Atas' },
            { value: 'looking-down', label: 'Melihat ke Bawah' },
            { value: 'looking-off-into-the-distance', label: 'Melihat ke kejauhan' },
        ]
    },
    {
        label: 'Sudut Dinamis & Pergerakan',
        options: [
            { value: 'tracking-shot', label: 'Mengikuti Objek (Tracking Shot)' },
            { value: 'panning-shot', label: 'Kamera Bergerak Horizontal (Panning)' },
            { value: 'whip-pan', label: 'Gerakan Cepat Horizontal (Whip Pan)' },
            { value: 'tilting-shot', label: 'Kamera Bergerak Vertikal (Tilting)' },
            { value: 'zoom-in', label: 'Zoom In (Mendekat)' },
            { value: 'zoom-out', label: 'Zoom Out (Menjauh)' },
            { value: 'dolly-zoom', label: 'Dolly Zoom (Efek Vertigo)' },
            { value: 'arc-shot', label: 'Mengitari Objek (Arc Shot)' },
            { value: 'handheld-shot', label: 'Genggaman Tangan (Handheld)' },
            { value: 'steadicam-shot', label: 'Steadicam Shot (Halus)' },
            { value: 'crane-shot', label: 'Diambil dari Derek (Crane Shot)' },
            { value: 'running-shot', label: 'Mengikuti Sambil Berlari' },
            { value: 'slow-motion', label: 'Gerak Lambat (Slow Motion)' },
            { value: 'fast-motion', label: 'Gerak Cepat (Fast Motion)' },
        ]
    },
    {
        label: 'Angle Kreatif & Lensa',
        options: [
            { value: 'dutch-angle', label: 'Angle Miring (Dutch Angle)' },
            { value: 'canted-angle', label: 'Angle Miring (Canted)' },
            { value: 'point-of-view-shot', label: 'Sudut Pandang (POV)' },
            { value: 'selfie-angle', label: 'Angle Selfie' },
            { value: 'vlogging-angle', label: 'Angle Vlogging' },
            { value: 'drone-shot', label: 'Angle Drone' },
            { value: 'reflection-shot', label: 'Pantulan (Cermin/Air)' },
            { value: 'shooting-through-object', label: 'Diambil menembus objek (kaca, daun)' },
            { value: 'through-the-legs-shot', label: 'Diambil dari sela-sela kaki' },
            { value: 'fisheye-lens-effect', label: 'Efek Lensa Fisheye' },
            { value: 'telephoto-compression', label: 'Kompresi Lensa Telefoto' },
            { value: 'wide-angle-distortion', label: 'Distorsi Lensa Wide' },
            { value: 'anamorphic-lens-flare', label: 'Anamorphic Lens Flare' },
            { value: 'lens-flare-effect', label: 'Efek Lens Flare' },
            { value: 'shallow-depth-of-field', label: 'Depth of Field Dangkal (Bokeh)' },
            { value: 'deep-focus', label: 'Fokus Tajam Menyeluruh (Deep Focus)' },
            { value: 'rack-focus', label: 'Pindah Fokus (Rack Focus)' },
            { value: 'split-diopter-shot', label: 'Split Diopter (Fokus Dekat & Jauh)' },
            { value: 'forced-perspective', label: 'Perspektif Paksa' },
            { value: 'tilt-shift-effect', label: 'Efek Tilt-shift (Miniatur)' },
        ]
    },
    {
        label: 'Komposisi',
        options: [
            { value: 'centered-composition', label: 'Komposisi di Tengah' },
            { value: 'rule-of-thirds-composition', label: 'Komposisi Rule of Thirds' },
            { value: 'golden-ratio-composition', label: 'Komposisi Golden Ratio' },
            { value: 'golden-triangle-composition', label: 'Komposisi Segitiga Emas' },
            { value: 'diagonal-composition', label: 'Komposisi Diagonal' },
            { value: 'symmetrical-composition', label: 'Komposisi Simetris' },
            { value: 'asymmetrical-composition', label: 'Komposisi Asimetris' },
            { value: 'leading-lines-composition', label: 'Komposisi Garis Pemandu' },
            { value: 'frame-within-a-frame', label: 'Bingkai di dalam Bingkai' },
            { value: 'negative-space-composition', label: 'Komposisi Ruang Negatif' },
            { value: 'fill-the-frame-composition', label: 'Memenuhi Bingkai (Fill Frame)' },
            { value: 'pattern-and-repetition', label: 'Pola dan Pengulangan' },
            { value: 'head-room-composition', label: 'Memberi Jarak Kepala (Head Room)' },
            { value: 'lead-room-composition', label: 'Memberi Ruang Gerak (Lead Room)' },
            { value: 'rule-of-space', label: 'Rule of Space' },
        ]
    },
    {
        label: 'Pencahayaan & Bayangan',
        options: [
            { value: 'silhouette-shot', label: 'Siluet (Menghadap Cahaya)' },
            { value: 'backlit-shot', label: 'Cahaya dari Belakang (Backlit)' },
            { value: 'rim-lighting', label: 'Cahaya Pinggir (Rim Lighting)' },
            { value: 'hard-light-with-shadows', label: 'Cahaya Keras dengan Bayangan' },
            { value: 'soft-diffused-light', label: 'Cahaya Lembut (Diffused)' },
            { value: 'split-lighting', label: 'Pencahayaan Separuh Wajah (Split)' },
            { value: 'chiaroscuro-lighting', label: 'Pencahayaan Chiaroscuro (Kontras Tinggi)' },
        ]
    }
];

export const backgroundOptions: OptionGroup[] = [
    {
        label: 'Warna Solid & Gradasi',
        options: [
            { value: 'solid-white-background', label: 'Putih Polos' },
            { value: 'solid-light-gray-background', label: 'Abu-abu Muda Polos' },
            { value: 'solid-dark-gray-background', label: 'Abu-abu Tua Polos' },
            { value: 'solid-black-background', label: 'Hitam Polos' },
            { value: 'solid-pastel-pink-background', label: 'Pink Pastel Polos' },
            { value: 'solid-pastel-blue-background', label: 'Biru Pastel Polos' },
            { value: 'solid-pastel-green-background', label: 'Hijau Pastel Polos' },
            { value: 'solid-pastel-yellow-background', label: 'Kuning Pastel Polos' },
            { value: 'solid-vibrant-red-background', label: 'Merah Terang Polos' },
            { value: 'solid-vibrant-blue-background', label: 'Biru Terang Polos' },
            { value: 'solid-neon-green-background', label: 'Hijau Neon Polos' },
            { value: 'soft-gradient-background', label: 'Gradasi Warna Lembut' },
            { value: 'vibrant-gradient-background', label: 'Gradasi Warna Terang' },
            { value: 'sunset-gradient-background', label: 'Gradasi Matahari Terbenam' },
            { value: 'ocean-gradient-background', label: 'Gradasi Lautan' },
        ]
    },
    {
        label: 'Interior & Ruangan',
        options: [
            { value: 'modern-living-room', label: 'Ruang Tamu Modern' },
            { value: 'cozy-living-room-with-fireplace', label: 'Ruang Tamu Nyaman (Perapian)' },
            { value: 'scandinavian-style-room', label: 'Ruangan Gaya Skandinavia' },
            { value: 'minimalist-room', label: 'Ruangan Minimalis' },
            { value: 'industrial-loft', label: 'Loteng Gaya Industri' },
            { value: 'bohemian-bedroom', label: 'Kamar Tidur Bohemian' },
            { value: 'modern-kitchen', label: 'Dapur Modern' },
            { value: 'rustic-kitchen', label: 'Dapur Pedesaan (Rustic)' },
            { value: 'home-office', label: 'Kantor di Rumah' },
            { value: 'corporate-office-blurry', label: 'Kantor Perusahaan (Blur)' },
            { value: 'library-with-bookshelves', label: 'Perpustakaan (Rak Buku)' },
            { value: 'cozy-cafe-interior', label: 'Interior Kafe yang Nyaman' },
            { value: 'luxury-restaurant', label: 'Restoran Mewah' },
            { value: 'art-gallery-with-paintings', label: 'Galeri Seni (Lukisan)' },
            { value: 'museum-interior', label: 'Interior Museum' },
            { value: 'gym-with-equipment', label: 'Gym (Peralatan)' },
            { value: 'dance-studio-with-mirrors', label: 'Studio Tari (Cermin)' },
            { value: 'greenhouse-interior', label: 'Interior Rumah Kaca' },
        ]
    },
    {
        label: 'Pemandangan Alam',
        options: [
            { value: 'tropical-beach-at-sunset', label: 'Pantai Tropis (Matahari Terbenam)' },
            { value: 'serene-beach-daylight', label: 'Pantai Tenang (Siang Hari)' },
            { value: 'lush-green-forest', label: 'Hutan Hijau Lebat' },
            { value: 'misty-forest-in-the-morning', label: 'Hutan Berkabut Pagi Hari' },
            { value: 'bamboo-forest', label: 'Hutan Bambu' },
            { value: 'snowy-mountain-peak', label: 'Puncak Gunung Bersalju' },
            { value: 'mountain-valley-landscape', label: 'Pemandangan Lembah Gunung' },
            { value: 'rolling-green-hills', label: 'Perbukitan Hijau' },
            { value: 'vast-desert-with-dunes', label: 'Gurun Pasir Luas' },
            { value: 'dense-jungle-with-vines', label: 'Hutan Belantara (Rimbun)' },
            { value: 'majestic-waterfall', label: 'Air Terjun Megah' },
            { value: 'calm-lake-with-reflections', label: 'Danau Tenang (Pantulan)' },
            { value: 'frozen-lake', label: 'Danau Beku' },
            { value: 'winding-river-in-a-forest', label: 'Sungai Berkelok di Hutan' },
            { value: 'field-of-sunflowers', label: 'Ladang Bunga Matahari' },
            { value: 'lavender-field', label: 'Ladang Lavender' },
            { value: 'snowy-forest', label: 'Hutan Bersalju' },
            { value: 'african-savanna-with-acacia-trees', label: 'Sabana Afrika (Pohon Akasia)' },
            { value: 'underwater-coral-reef', label: 'Terumbu Karang Bawah Laut' },
            { value: 'volcanic-landscape', label: 'Pemandangan Vulkanik' },
        ]
    },
    {
        label: 'Perkotaan & Arsitektur',
        options: [
            { value: 'busy-city-street', label: 'Jalanan Kota yang Sibuk' },
            { value: 'tokyo-street-at-night-neon', label: 'Jalanan Tokyo Malam Hari (Neon)' },
            { value: 'rooftop-overlooking-cityscape', label: 'Atap Gedung (Pemandangan Kota)' },
            { value: 'empty-alleyway-at-night', label: 'Gang Sepi Malam Hari' },
            { value: 'modern-architectural-building', label: 'Gedung Arsitektur Modern' },
            { value: 'historic-european-street', label: 'Jalanan Bersejarah Eropa' },
            { value: 'grand-central-station', label: 'Stasiun Kereta Api Besar' },
            { value: 'modern-airport-terminal', label: 'Terminal Bandara Modern' },
            { value: 'industrial-warehouse', label: 'Gudang Industri' },
            { value: 'skyscraper-facade', label: 'Fasad Gedung Pencakar Langit' },
            { value: 'bridge-with-city-view', label: 'Jembatan (Pemandangan Kota)' },
            { value: 'subway-platform', label: 'Platform Kereta Bawah Tanah' },
            { value: 'university-campus', label: 'Kampus Universitas' },
            { value: 'skate-park', label: 'Taman Skateboard' },
            { value: 'amusement-park', label: 'Taman Hiburan' },
        ]
    },
    {
        label: 'Tekstur & Pola',
        options: [
            { value: 'exposed-brick-wall', label: 'Dinding Bata Ekspos' },
            { value: 'white-brick-wall', label: 'Dinding Bata Putih' },
            { value: 'weathered-wood-planks', label: 'Papan Kayu Lapuk' },
            { value: 'polished-concrete-wall', label: 'Dinding Beton Halus' },
            { value: 'marble-texture', label: 'Tekstur Marmer' },
            { value: 'geometric-pattern-wallpaper', label: 'Wallpaper Pola Geometris' },
            { value: 'floral-pattern-wallpaper', label: 'Wallpaper Pola Bunga' },
            { value: 'abstract-texture', label: 'Tekstur Abstrak' },
            { value: 'metallic-surface', label: 'Permukaan Metalik' },
            { value: 'fabric-drapery', label: 'Tirai Kain' },
            { value: 'mosaic-tile-wall', label: 'Dinding Ubin Mozaik' },
            { value: 'rusty-metal-sheet', label: 'Lembaran Logam Berkarat' },
        ]
    },
    {
        label: 'Abstrak & Konseptual',
        options: [
            { value: 'blurry-bokeh-lights', label: 'Lampu Bokeh (Blur)' },
            { value: 'colorful-light-streaks', label: 'Garis Cahaya Warna-warni' },
            { value: 'wispy-smoke-effect', label: 'Efek Asap Tipis' },
            { value: 'colorful-powder-explosion', label: 'Ledakan Bubuk Warna-warni' },
            { value: 'liquid-paint-splash', label: 'Percikan Cat Cair' },
            { value: 'abstract-geometric-shapes', label: 'Bentuk Geometris Abstrak' },
            { value: 'minimalist-lines', label: 'Garis-garis Minimalis' },
            { value: 'watercolor-wash-background', label: 'Sapuan Cat Air' },
            { value: 'digital-glitch-effect', label: 'Efek Glitch Digital' },
            { value: 'holographic-background', label: 'Holografik' },
            { value: 'paper-texture', label: 'Tekstur Kertas' },
            { value: 'plexiglass-effect', label: 'Efek Kaca Plexi' },
        ]
    },
    {
        label: 'Langit & Cuaca',
        options: [
            { value: 'clear-blue-sky-with-clouds', label: 'Langit Biru Cerah (Awan)' },
            { value: 'dramatic-sunset-sky', label: 'Langit Matahari Terbenam Dramatis' },
            { value: 'soft-sunrise-sky', label: 'Langit Matahari Terbit Lembut' },
            { value: 'starry-night-sky-with-milky-way', label: 'Langit Malam Berbintang (Bima Sakti)' },
            { value: 'stormy-sky-with-lightning', label: 'Langit Badai (Petir)' },
            { value: 'overcast-cloudy-sky', label: 'Langit Mendung' },
            { value: 'rainbow-in-the-sky', label: 'Pelangi di Langit' },
            { value: 'aurora-borealis', label: 'Aurora Borealis' },
            { value: 'foggy-weather', label: 'Cuaca Berkabut' },
            { value: 'heavy-rain', label: 'Hujan Deras' },
        ]
    },
    {
        label: 'Studio & Fotografi',
        options: [
            { value: 'photo-studio-white-cyclorama', label: 'Studio Foto (Layar Putih)' },
            { value: 'photo-studio-black-background', label: 'Studio Foto (Latar Hitam)' },
            { value: 'photo-studio-colored-backdrop', label: 'Studio Foto (Latar Berwarna)' },
            { value: 'seamless-paper-background', label: 'Kertas Latar Seamless' },
            { value: 'fashion-runway', label: 'Panggung Fashion Show' },
            { value: 'product-photography-setup', label: 'Set Foto Produk' },
            { value: 'behind-the-scenes-photoshoot', label: 'Di Balik Layar Sesi Foto' },
        ]
    },
    {
        label: 'Fantasi & Fiksi Iliah',
        options: [
            { value: 'enchanted-glowing-forest', label: 'Hutan Ajaib Bercahaya' },
            { value: 'medieval-castle-interior', label: 'Interior Kastil Abad Pertengahan' },
            { value: 'dragon-lair', label: 'Sarang Naga' },
            { value: 'alien-planet-landscape', label: 'Pemandangan Planet Asing' },
            { value: 'futuristic-city-cyberpunk', label: 'Kota Masa Depan (Cyberpunk)' },
            { value: 'spaceship-cockpit-interior', label: 'Interior Kokpit Pesawat Luar Angkasa' },
            { value: 'steampunk-city', label: 'Kota Steampunk' },
            { value: 'post-apocalyptic-ruins', label: 'Reruntuhan Pasca-kiamat' },
            { value: 'floating-islands-in-the-sky', label: 'Pulau-pulau Melayang di Langit' },
            { value: 'underwater-city', label: 'Kota Bawah Laut' },
        ]
    },
    {
        label: 'Event & Suasana',
        options: [
            { value: 'concert-stage-with-lights', label: 'Panggung Konser (Lampu)' },
            { value: 'birthday-party-with-balloons', label: 'Pesta Ulang Tahun (Balon)' },
            { value: 'wedding-ceremony-arch', label: 'Upacara Pernikahan' },
            { value: 'night-market-with-stalls', label: 'Pasar Malam (Kios)' },
            { value: 'nightclub-with-dance-floor', label: 'Klub Malam (Lantai Dansa)' },
            { value: 'cozy-fireplace-setting', label: 'Suasana Perapian yang Nyaman' },
            { value: 'carnival-with-ferris-wheel', label: 'Karnaval (Bianglala)' },
            { value: 'red-carpet-event', label: 'Acara Karpet Merah' },
            { value: 'music-festival-crowd', label: 'Festival Musik (Penonton)' },
            { value: 'bookstore-cafe', label: 'Toko Buku Kafe' },
        ]
    },
    {
        label: 'Ruang Kerja & Hobi',
        options: [
            { value: 'artist-studio-messy', label: 'Studio Seniman (Berantakan)' },
            { value: 'carpenters-workshop', label: 'Bengkel Tukang Kayu' },
            { value: 'science-laboratory', label: 'Laboratorium Sains' },
            { value: 'music-recording-studio', label: 'Studio Rekaman Musik' },
            { value: 'gamers-room-with-leds', label: 'Kamar Gamer (Lampu LED)' },
            { value: 'pottery-studio', label: 'Studio Tembikar' },
            { value: 'fashion-designers-studio', label: 'Studio Perancang Busana' },
            { value: 'writers-desk-with-typewriter', label: 'Meja Penulis (Mesin Tik)' },
        ]
    },
    {
        label: 'Edukasi & Pengetahuan',
        options: [
            { value: 'modern-classroom', label: 'Ruang Kelas Modern' },
            { value: 'university-lecture-hall', label: 'Aula Kuliah Universitas' },
            { value: 'science-museum-exhibit', label: 'Pameran Museum Sains' },
            { value: 'chalkboard-with-equations', label: 'Papan Tulis Kapur (Rumus)' },
            { value: 'whiteboard-with-diagrams', label: 'Papan Tulis Putih (Diagram)' },
        ]
    },
    {
        label: 'Sejarah & Vintage',
        options: [
            { value: 'vintage-room-with-antique-furniture', label: 'Ruangan Vintage (Furnitur Antik)' },
            { value: 'ancient-ruins', label: 'Reruntuhan Kuno' },
            { value: 'victorian-era-street', label: 'Jalanan Era Victoria' },
            { value: '1920s-speakeasy-bar', label: 'Bar Speakeasy 1920-an' },
            { value: 'old-paper-or-parchment-texture', label: 'Tekstur Kertas Tua' },
        ]
    },
];

export const resolutionOptions: SelectOption[] = [
    { value: '1k', label: '1K (Standard)' },
    { value: '2k', label: '2K (High Quality)' },
    { value: '4k', label: '4K (Ultra High)' },
];